#!/bin/bash 

dotfiles=("bashrc" "gitconfig" "vimrc")

for dotfile in "${dotfiles[@]}"
do
	if [ -e ~/.$dotfile ]
	then
		echo ".$dotfile already created."
	else
		echo "Creating .$dotfile..."
		ln -s ~/dotfiles/$dotfile ~/.$dotfile
		
	fi
done
